version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8087:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb